name: Lint

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --no-fund

      - name: Lint
        run: ./node_modules/.bin/stylelint "styles/*.css"
